### ISSUE TITLE
Thermostat temperature wrong by factor of 10

### ISSUE THREAD

**Issue by vbartels** [tuya/tuya-homebridge#268]
I have a heated mirror (DMS SIH-600, shows up as "heater device (wifi)") wich shows up and works but the values are wrong by a factor of 10. On/Off switch works as expected. The Input in Homekit App allows values between 0°C and 370°C. wich seems to reflect the max temp of the device of 37°C. Dialing in 168°C results in a setting of 16°C.
The current temperature shown seems to be always 122,0°C. The Logs show:
`[27/07/2022, 10:12:05] [homebridge-tuya-platform] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 190 exceeded maximum of 122. See https://homebridge.io/w/JtMGR for more info.
` 
Where 190 seems to reflect the 19°C shown in the Tuya app.

**Expected behavior**
I would expect a temp range from 0°C to 37°C as in the Tuya app. And the current Temperature reflecting the actual value instead of showing 122°C all the time, even when the heater is off.

![IMG_1111](https://user-images.githubusercontent.com/25765286/181213763-627099cb-d75e-4419-8766-5d720638bfc2.PNG)
![IMG_1112](https://user-images.githubusercontent.com/25765286/181213771-31c524f3-7884-4086-a0ca-d4fe211d4e50.PNG)
![IMG_1113](https://user-images.githubusercontent.com/25765286/181213778-876fac2f-e6c8-4ecb-a779-59b5a5080ba1.PNG)
![IMG_1114](https://user-images.githubusercontent.com/25765286/181213782-fc500738-a393-4899-b0c0-1d549e2b3ccd.PNG)

`TuyaOpenAPI response: {"result":[{"category":"qn","devices":["063603439c9c1f44ed2c"],"functions":[{"code":"switch","desc":"switch","name":"switch","type":"Boolean","values":"{}"},{"code":"temp_set","desc":"temp set","name":"temp set","type":"Integer","values":"{\"unit\":\"℃\",\"min\":0,\"max\":370,\"scale\":1,\"step\":10}"},{"code":"c_f","desc":"c f","name":"c f","type":"Enum","values":"{\"range\":[\"C\",\"F\"]}"}],"product_id":"4aVbNfxEYUbylvvW"}],"success":true,"t":1658913513102,"tid":"1617ca160d8d11eda506322e56e3d437"} path = /v1.0/devices/functions`

**Comment by vbartels** [comment]
This pull request: https://github.com/xlinur/tuya-homebridge/pull/1/files claims to have this fixed.... I've no way to check?!

**Comment by vbartels** [comment]
Nothing changed, how can I help? Are more informations needed?

**Comment by 0x5e** [comment]
@vbartels please try `@0x5e/homebridge-tuya-platform`, it has been fixed.

**Comment by recoi1er** [comment]
> @vbartels please try `@0x5e/homebridge-tuya-platform`, it has been fixed.

I just installed a heater today and the issue is still there

![2969A8F8-4678-4BDD-9A22-2E722D3F66BA](https://user-images.githubusercontent.com/19810634/204919433-a6bbc3b9-1c03-4591-8a13-334cc3e4248f.png)


plugin is v1.5.0 (released over a year ago?) and no available updates to apply - what do you mean by “please try `@0x5e/homebridge-tuya-platform`“?

**Comment by 0x5e** [comment]
@recoi1er It's fixed in https://github.com/0x5e/homebridge-tuya-platform/pull/38, please install `@0x5e/homebridge-tuya-platform` instead of `homebridge-tuya-platform`

**Comment by recoi1er** [comment]
> @recoi1er It's fixed in [0x5e#20](https://github.com/0x5e/homebridge-tuya-platform/pull/20), please install `@0x5e/homebridge-tuya-platform` instead of `homebridge-tuya-platform`

I don’t understand, what is 0x5e?

**Comment by recoi1er** [comment]
> @recoi1er It's fixed in [0x5e#20](https://github.com/0x5e/homebridge-tuya-platform/pull/20), please install `@0x5e/homebridge-tuya-platform` instead of `homebridge-tuya-platform`

I don’t understand, what is 0x5e?

**Comment by Sch011** [comment]
@0x5e does the fix only apply on Fahrenheit degrees? Cuz I’m currently using the plugin you suggested to, I’ve tried both 1.6 and 1.7 (beta) versions and I do have some trouble with my thermostat that are using Celsius degrees; basically the setting temperature (in tuya and on the thermostat) is always the half of the one requested from HomeKit, the temperature detector in the room (by HomeKit) is always five time less than the real one (showed in tuya and on the thermostat).

**Comment by 0x5e** [comment]
> @0x5e does the fix only apply on Fahrenheit degrees? Cuz I’m currently using the plugin you suggested to, I’ve tried both 1.6 and 1.7 (beta) versions and I do have some trouble with my thermostat that are using Celsius degrees; basically the setting temperature (in tuya and on the thermostat) is always the half of the one requested from HomeKit, the temperature detector in the room (by HomeKit) is always five time less than the real one (showed in tuya and on the thermostat).

Not only Fahrenheit degrees, it can transform any schema you want.

**Comment by Sch011** [comment]
> > @0x5e does the fix only apply on Fahrenheit degrees? Cuz I’m currently using the plugin you suggested to, I’ve tried both 1.6 and 1.7 (beta) versions and I do have some trouble with my thermostat that are using Celsius degrees; basically the setting temperature (in tuya and on the thermostat) is always the half of the one requested from HomeKit, the temperature detector in the room (by HomeKit) is always five time less than the real one (showed in tuya and on the thermostat).
> 
> Not only Fahrenheit degrees, it can transform any schema you want.

May you tell me how can I do that, I would really appreciate, thanks

**Comment by 0x5e** [comment]
The example is below, please try if it solves your problem:
https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md#adjust-integer-schema-ranges

**Comment by Sch011** [comment]
> @Sch011 The example is below, please try if it solves your problem:
> https://github.com/0x5e/homebridge-tuya-platform/blob/develop_1.7.0/ADVANCED_OPTIONS.md#adjust-integer-schema-ranges

It may sound really stupid but i really don’t know what to add in “oldCode” and “newCode” I’ve done everything else, fixed the scale and the math to match the numbers, but the schema fails probably because of the new/old code; sorry if I’m bothering I’m trying, I’m kinda new. Thanks

**Comment by 0x5e** [comment]
@Sch011 Using `onGet` and `onSet` to adjust the values, like this:
```
        "onGet": "(value * 5);",
        "onSet": "(value / 5);",
```

**Comment by Sch011** [comment]
> @Sch011 Using `onGet` and `onSet` to adjust the values, like this:
> 
> ```
>         "onGet": "(value * 5);",
>         "onSet": "(value / 5);",
> ```

Thanks again

**Comment by Sch011** [comment]
@0x5e Hi, as you may see the temperature below is 21 as it should be, thanks to the suggestion you gave me, but the one above ( the detected one) is only 3,5, I’ve bene trying adding different lines of code or modify the existing ones but I never figured how to fix the actual room’s temperature value, is there a way to? 
![160A6078-0C74-4F2F-AB61-408AAA1181FD](https://user-images.githubusercontent.com/120411726/209545476-b5d265e7-f383-490b-8804-4a8ac90bb32a.png)

**Comment by 0x5e** [comment]
> @0x5e Hi, as you may see the temperature below is 21 as it should be, thanks to the suggestion you gave me, but the one above ( the detected one) is only 3,5, I’ve bene trying adding different lines of code or modify the existing ones but I never figured how to fix the actual room’s temperature value, is there a way to? ![160A6078-0C74-4F2F-AB61-408AAA1181FD](https://user-images.githubusercontent.com/120411726/209545476-b5d265e7-f383-490b-8804-4a8ac90bb32a.png)

Please upload the original schema of the target temperature and current temperature, let me have a look.

**Comment by Sch011** [comment]
@0x5e That’s the code I’ve ended up with
![25E88C1C-FF5D-4C06-8F47-26CE932F6A44](https://user-images.githubusercontent.com/120411726/209561606-5fc0503e-5cc2-4b21-a11e-e90bb6324c15.jpeg)

**Comment by 0x5e** [comment]
@Sch011 I need the original schema from the device info json, which can be found(the filepath) from the log.

**Comment by Sch011** [comment]
@0x5e Thanks to you I’ve found the original schema and I managed to modify the schema by myself cuz I didn’t want to bother you more than I did; I do really appreciate every tip you gave me thanks again and have a nice one ^^

**Comment by vbartels** [comment]
I switched to @0x5e s fork and it works for me, too. Thanks!

**Comment by BusinessGuysIT** [comment]
To confirm, having the same issue, https://snipboard.io/n0mesI.jpg

Is it only working in the beta then?
