### ISSUE TITLE
Names identical when using Homebridge

### ISSUE THREAD

**Issue by g33z3riley** [tuya/tuya-homebridge#93]
When I'm linking the homebridge to node-red each accessory has identical names i.e:
<img width="622" alt="Screen_Snip" src="https://user-images.githubusercontent.com/86230495/130288170-fad2bec9-8973-4b53-bc5e-7b118ea1fa45.png">
It makes it impossible to select anything except the first instance - is there any way of making sure the identifier for each switch is somehow different like even including a bit of the mac address or something? I've tried changing the names in homebridge and on the Tuya app but neither has any effect - node-red seems to pull the generic type and switch names whatever I do. Thank you!

**Comment by Hanh94** [comment]
Hi @g33z3riley , Please provide more device details log according to the issue template.

**Comment by Hanh94** [comment]
Hi @g33z3riley ,Sorry for the late reply
We have fixed it in 1.4.2, please upgrade and try again

**Comment by pratsenka** [comment]
Helo
Confirm problem remains in homebridge-tuya-platform v1.5.0

**Comment by reshadf** [comment]
Same here, once added the same name the previous devices stop working.
